<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.3.2.295
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма Золотой резерв Поставки свежемороженой рыбы по всейРоссии от рыбодобывающих компаний',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'nadezhda.arbuzova2014@yandex.ru',
		'to' => 'nadezhda.arbuzova2014@yandex.ru'
	),
	'fields' => array(
		'custom_U1182' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Имя',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Имя\' не может быть пустым.'
			)
		),
		'Email' => array(
			'order' => 14,
			'type' => 'email',
			'label' => '1234',
			'required' => false,
			'errors' => array(
				'required' => 'Поле \'1234\' не может быть пустым.',
				'format' => 'Поле \'1234\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U1190' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Наименование рыбы',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Наименование рыбы\' не может быть пустым.'
			)
		),
		'custom_U1164' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Вид разделки',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Вид разделки\' не может быть пустым.'
			)
		),
		'custom_U1152' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Размер',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Размер\' не может быть пустым.'
			)
		),
		'custom_U1204' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Тара',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Тара\' не может быть пустым.'
			)
		),
		'custom_U1186' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Производитель',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Производитель\' не может быть пустым.'
			)
		),
		'custom_U1156' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Дата вылова',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Дата вылова\' не может быть пустым.'
			)
		),
		'custom_U1208' => array(
			'order' => 13,
			'type' => 'string',
			'label' => 'Срок годности',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Срок годности\' не может быть пустым.'
			)
		),
		'custom_U1170' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Место отгрузки',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Место отгрузки\' не может быть пустым.'
			)
		),
		'custom_U1160' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Объем',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Объем\' не может быть пустым.'
			)
		),
		'custom_U1194' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Цена',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Цена\' не может быть пустым.'
			)
		),
		'custom_U1199' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Название вашей компании',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Название вашей компании\' не может быть пустым.'
			)
		),
		'custom_U1178' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Телефон',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Телефон\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
