$axure.loadCurrentPage({
  "url":"наведение_на_блок_перехода_в_раздел.html",
  "generationDate":new Date(1548335086782.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f9df25b0588344d793fc2dd45b38cf3e",
    "type":"Axure:Page",
    "name":"Наведение на блок перехода в раздел",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ec41fc9035a43d7bf39ba4e0d0312d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
}},
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"507ba098993b4a62bdc8e0688db882b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
}},
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u10.png"}},
{
          "id":"5c061e6fe8f04166bfc4c5b38fad685f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":50,
              "y":30},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffb460b189f141f19c262a8cdda98375",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":50,
                  "y":30},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u12.png"}},
{
          "id":"0ce72696075745dc99b7d8a738d9f429",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":148,
              "y":40},
            "size":{
              "width":132,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"426f2db567514b8aa1848833552d8108",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":148,
                  "y":40},
                "size":{
                  "width":132,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1413ae31bba45e38dee78deb9d31f64",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":148,
              "y":90},
            "size":{
              "width":106,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ca3950b1a8c4ccf8cbb3afef43c2b76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":148,
                  "y":90},
                "size":{
                  "width":106,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5f0965bf1c848e3be6ad483d94911b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":259,
              "y":92},
            "size":{
              "width":11,
              "height":11},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94b52dffac014be390516fb3903d71db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":259,
                  "y":92},
                "size":{
                  "width":11,
                  "height":11},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u24.png"}},
{
          "id":"6a663973ef4e4bdcb1be756843575b85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":178},
            "size":{
              "width":86,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e35e1f0ec12d48e4834dc42bc0c31f91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":178},
                "size":{
                  "width":86,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03e7e096e08e461c8bc5adef22fe752b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":40,
              "y":138},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b96736f11b804f7f876bc573916cd18e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":138},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53354ced8df34686958ccb897c352f99",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
}},
            "location":{
              "x":390,
              "y":20},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b1853eb19e44aafbf7d0c11056906bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
}},
                "location":{
                  "x":390,
                  "y":20},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u10.png"}},
{
          "id":"c1db679c82ba45a18632b1422ff52b17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":400,
              "y":30},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5d385b8cb1242cfa824d3d6ea8a684f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":400,
                  "y":30},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u12.png"}},
{
          "id":"fa73ba53ba374ca2b9d0395316cb5214",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":498,
              "y":40},
            "size":{
              "width":132,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"086642e614e141c782da7c8c317dd34c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":498,
                  "y":40},
                "size":{
                  "width":132,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a617e49af081462faad8a55e8c7580e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":498,
              "y":90},
            "size":{
              "width":106,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c651cade3c4cdb97455871a5798851",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":498,
                  "y":90},
                "size":{
                  "width":106,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"760ad525d54143478d7062396b3267a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":390,
              "y":138},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83c91be2c2784974a8120ac765b61ff9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":138},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c82a512dae444034b6bcbdb741382d03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
}},
            "location":{
              "x":40,
              "y":263},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccd22ebce887410b8fabe9929082329d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
}},
                "location":{
                  "x":40,
                  "y":263},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u10.png"}},
{
          "id":"f40f5fbf8d964a029bbdacbebc7704f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":50,
              "y":273},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b872911c092a4f278c894f92388d0b15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":50,
                  "y":273},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u12.png"}},
{
          "id":"ce25c06caa6e4a8fb712d1f2572e2e2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":148,
              "y":283},
            "size":{
              "width":132,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfcdfb105a2b4f02a99e1c2fcea7aa2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":148,
                  "y":283},
                "size":{
                  "width":132,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"152acdb6df5346758ef14b3950ae31f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":421},
            "size":{
              "width":86,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51b7c71cac644dfeaea28776aa7a3467",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":421},
                "size":{
                  "width":86,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef5d95556f7d4485857ae504e0e943a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":40,
              "y":381},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc5c3cfd2be54c648ca2ef8109fab26b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":381},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8463a70437c4b19b6f361431e0f0755",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
}},
            "location":{
              "x":390,
              "y":263},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23a103896c7949ac833976636896c311",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
}},
                "location":{
                  "x":390,
                  "y":263},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u10.png"}},
{
          "id":"26ae737c682b4c81bb46fa6e105a56d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":400,
              "y":273},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f94bb5f2f26f441f982f5f7749d54ea9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":400,
                  "y":273},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u12.png"}},
{
          "id":"d7b5120004ff44d5a1f383225f63156b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":498,
              "y":283},
            "size":{
              "width":132,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d48a3a9d9994f1f90371891bd42c029",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":498,
                  "y":283},
                "size":{
                  "width":132,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"028dd5e452074ee8b284c9131720f74d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":390,
              "y":381},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bace45f652445ae848d3db114ec0a62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":381},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4204c9e22b364200847dfa0cb58292f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":498,
              "y":333},
            "size":{
              "width":106,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e822c3598e647e9b88e3307580e020e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":498,
                  "y":333},
                "size":{
                  "width":106,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf8812245e1c4095a507827acc86005d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":609,
              "y":335},
            "size":{
              "width":11,
              "height":11},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83af3657d4284cb7860975b82f21aac7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":609,
                  "y":335},
                "size":{
                  "width":11,
                  "height":11},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u24.png"}},
{
          "id":"4867d2686a044645a7029e933dbf1fc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
}},
            "location":{
              "x":40,
              "y":507},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee19f67e060d4813b2e3064e8491820b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
}},
                "location":{
                  "x":40,
                  "y":507},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u10.png"}},
{
          "id":"36132076dcde44c0ae6e43d9452d5351",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":50,
              "y":517},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e1d3ba935154cc18e3956e8fc6ac195",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":50,
                  "y":517},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u12.png"}},
{
          "id":"a13fdbc1e5f5478ea27dc54c2854a9de",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":148,
              "y":527},
            "size":{
              "width":132,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7e1d4ab62e4aeca75d078574b4e3df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":148,
                  "y":527},
                "size":{
                  "width":132,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3542fe610ba34055a22f170555e66dca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":665},
            "size":{
              "width":86,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1792fbc472a74fe495b6ecd590a13582",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":665},
                "size":{
                  "width":86,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8510bac8346479b9ea33a3032e76b5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":40,
              "y":625},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"876460e12f274062b04507f8bd11c748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":625},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11cfcb10b7af41f88919f3c52bd09b1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":390,
              "y":507},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e29c4f9b1bf34a5eb6129a61540717c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":390,
                  "y":507},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u10_mouseOver.png"}},
{
          "id":"7f941e90cd40459b919044ee7baffa88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":400,
              "y":517},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"454015f0ee3f4e8896116a058c17f353",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":400,
                  "y":517},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u12.png"}},
{
          "id":"1e4ccc02360d4280a2c021e6e3488fe8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":498,
              "y":527},
            "size":{
              "width":132,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"015a8de6eec043beab07f8967a628034",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":498,
                  "y":527},
                "size":{
                  "width":132,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"033bab825205441bb3df57cc050b6c3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":390,
              "y":625},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6d01e727bf144309f73d3628770cad9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":625},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bee2bc8230548f99a53f910e3bb7db6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":498,
              "y":577},
            "size":{
              "width":106,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ed291ee15e2466094186cf175779b8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":498,
                  "y":577},
                "size":{
                  "width":106,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6fc7a2c2a2b4a938f6287f5820490aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":609,
              "y":579},
            "size":{
              "width":11,
              "height":11},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1bda09c596c4c90a6324b9e05d10ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":609,
                  "y":579},
                "size":{
                  "width":11,
                  "height":11},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u24.png"}},
{
          "id":"ded81012f7e048ba8bbcd5f358ea1898",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":148,
              "y":577},
            "size":{
              "width":106,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"042f59d841f44ae7892647f125f8ab7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":148,
                  "y":577},
                "size":{
                  "width":106,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8577f75afc6746d19e06eacd38efaad0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":259,
              "y":579},
            "size":{
              "width":11,
              "height":11},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcd10b7d561643ef978f2c15417ad68e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":259,
                  "y":579},
                "size":{
                  "width":11,
                  "height":11},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u24.png"}},
{
          "id":"edde79b9904044628971161ffb813530",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
}},
            "location":{
              "x":40,
              "y":750},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b63609f2f22c48c090015b9d01a2d653",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
}},
                "location":{
                  "x":40,
                  "y":750},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u10.png"}},
{
          "id":"1795c77b6b8a461db44717ce3c05acfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":50,
              "y":760},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8ffe87da73b467f9308abdc34470668",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":50,
                  "y":760},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u12.png"}},
{
          "id":"5e23422290164e64b96a433d0e43a7ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":148,
              "y":770},
            "size":{
              "width":132,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c13a83f6de64483eafdf0262edc6af57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":148,
                  "y":770},
                "size":{
                  "width":132,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d3c1bb0cbae44c3be5ecd450a8e0d48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":40,
              "y":908},
            "size":{
              "width":86,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"793b3121c4f94bb2b5cf0586a53f83ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":40,
                  "y":908},
                "size":{
                  "width":86,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15d635ef19014af8854306656bd94b18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":40,
              "y":868},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c793123a3a5406a9d1a4d7dc9c277a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":868},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b77860d1bfa24665a40d77a3e8760361",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
}},
            "location":{
              "x":390,
              "y":750},
            "size":{
              "width":300,
              "height":100},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":215,
                "g":215,
                "b":215,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebc98fb19c7541d09cb958d9ffe2ae2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
}},
                "location":{
                  "x":390,
                  "y":750},
                "size":{
                  "width":300,
                  "height":100},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":215,
                    "g":215,
                    "b":215,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/наведение_на_блок_перехода_в_раздел/u82.png"}},
{
          "id":"369e7ea2f40f4cde94f273b2ac3b18b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":400,
              "y":760},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e23902586343474bb15c95b577b26b40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":400,
                  "y":760},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u12.png"}},
{
          "id":"8fc2521e2a0542039e0d29d560fafe62",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":498,
              "y":770},
            "size":{
              "width":132,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"574c456cca2a45cfa3c4ed3846ea5d86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":498,
                  "y":770},
                "size":{
                  "width":132,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c5b431a2fc74cba85bc380524789c5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":390,
              "y":868},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18e93c5375e2437a8062ed92178f992c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":868},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12eb6e46f04c4f3f8034a76c1637d47d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":498,
              "y":820},
            "size":{
              "width":106,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f113087bc3c14c2ebc88b98b36771906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":498,
                  "y":820},
                "size":{
                  "width":106,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7457e76f80740e1a87f8fa96d2ea4b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":609,
              "y":822},
            "size":{
              "width":11,
              "height":11},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a701890e7924da3b30a099238f8021e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":609,
                  "y":822},
                "size":{
                  "width":11,
                  "height":11},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u24.png"}},
{
          "id":"ae69b32e3ec24917a2a8914d706242cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":148,
              "y":820},
            "size":{
              "width":106,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ad30707ecdf4e15bd4c72ca9f808889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":148,
                  "y":820},
                "size":{
                  "width":106,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2a5aee6635e48d18e31ab5dbf797eb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":259,
              "y":822},
            "size":{
              "width":11,
              "height":11},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"154106a770cc4c6e8c17ff196f0c7b5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":259,
                  "y":822},
                "size":{
                  "width":11,
                  "height":11},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5ec41fc9035a43d7bf39ba4e0d0312d6":{
      "scriptId":"u0"},
    "507ba098993b4a62bdc8e0688db882b5":{
      "scriptId":"u1"},
    "5c061e6fe8f04166bfc4c5b38fad685f":{
      "scriptId":"u2"},
    "ffb460b189f141f19c262a8cdda98375":{
      "scriptId":"u3"},
    "0ce72696075745dc99b7d8a738d9f429":{
      "scriptId":"u4"},
    "426f2db567514b8aa1848833552d8108":{
      "scriptId":"u5"},
    "d1413ae31bba45e38dee78deb9d31f64":{
      "scriptId":"u6"},
    "8ca3950b1a8c4ccf8cbb3afef43c2b76":{
      "scriptId":"u7"},
    "b5f0965bf1c848e3be6ad483d94911b6":{
      "scriptId":"u8"},
    "94b52dffac014be390516fb3903d71db":{
      "scriptId":"u9"},
    "6a663973ef4e4bdcb1be756843575b85":{
      "scriptId":"u10"},
    "e35e1f0ec12d48e4834dc42bc0c31f91":{
      "scriptId":"u11"},
    "03e7e096e08e461c8bc5adef22fe752b":{
      "scriptId":"u12"},
    "b96736f11b804f7f876bc573916cd18e":{
      "scriptId":"u13"},
    "53354ced8df34686958ccb897c352f99":{
      "scriptId":"u14"},
    "2b1853eb19e44aafbf7d0c11056906bd":{
      "scriptId":"u15"},
    "c1db679c82ba45a18632b1422ff52b17":{
      "scriptId":"u16"},
    "b5d385b8cb1242cfa824d3d6ea8a684f":{
      "scriptId":"u17"},
    "fa73ba53ba374ca2b9d0395316cb5214":{
      "scriptId":"u18"},
    "086642e614e141c782da7c8c317dd34c":{
      "scriptId":"u19"},
    "a617e49af081462faad8a55e8c7580e3":{
      "scriptId":"u20"},
    "43c651cade3c4cdb97455871a5798851":{
      "scriptId":"u21"},
    "760ad525d54143478d7062396b3267a9":{
      "scriptId":"u22"},
    "83c91be2c2784974a8120ac765b61ff9":{
      "scriptId":"u23"},
    "c82a512dae444034b6bcbdb741382d03":{
      "scriptId":"u24"},
    "ccd22ebce887410b8fabe9929082329d":{
      "scriptId":"u25"},
    "f40f5fbf8d964a029bbdacbebc7704f0":{
      "scriptId":"u26"},
    "b872911c092a4f278c894f92388d0b15":{
      "scriptId":"u27"},
    "ce25c06caa6e4a8fb712d1f2572e2e2a":{
      "scriptId":"u28"},
    "bfcdfb105a2b4f02a99e1c2fcea7aa2c":{
      "scriptId":"u29"},
    "152acdb6df5346758ef14b3950ae31f1":{
      "scriptId":"u30"},
    "51b7c71cac644dfeaea28776aa7a3467":{
      "scriptId":"u31"},
    "ef5d95556f7d4485857ae504e0e943a6":{
      "scriptId":"u32"},
    "cc5c3cfd2be54c648ca2ef8109fab26b":{
      "scriptId":"u33"},
    "d8463a70437c4b19b6f361431e0f0755":{
      "scriptId":"u34"},
    "23a103896c7949ac833976636896c311":{
      "scriptId":"u35"},
    "26ae737c682b4c81bb46fa6e105a56d5":{
      "scriptId":"u36"},
    "f94bb5f2f26f441f982f5f7749d54ea9":{
      "scriptId":"u37"},
    "d7b5120004ff44d5a1f383225f63156b":{
      "scriptId":"u38"},
    "4d48a3a9d9994f1f90371891bd42c029":{
      "scriptId":"u39"},
    "028dd5e452074ee8b284c9131720f74d":{
      "scriptId":"u40"},
    "6bace45f652445ae848d3db114ec0a62":{
      "scriptId":"u41"},
    "4204c9e22b364200847dfa0cb58292f3":{
      "scriptId":"u42"},
    "0e822c3598e647e9b88e3307580e020e":{
      "scriptId":"u43"},
    "bf8812245e1c4095a507827acc86005d":{
      "scriptId":"u44"},
    "83af3657d4284cb7860975b82f21aac7":{
      "scriptId":"u45"},
    "4867d2686a044645a7029e933dbf1fc2":{
      "scriptId":"u46"},
    "ee19f67e060d4813b2e3064e8491820b":{
      "scriptId":"u47"},
    "36132076dcde44c0ae6e43d9452d5351":{
      "scriptId":"u48"},
    "0e1d3ba935154cc18e3956e8fc6ac195":{
      "scriptId":"u49"},
    "a13fdbc1e5f5478ea27dc54c2854a9de":{
      "scriptId":"u50"},
    "7b7e1d4ab62e4aeca75d078574b4e3df":{
      "scriptId":"u51"},
    "3542fe610ba34055a22f170555e66dca":{
      "scriptId":"u52"},
    "1792fbc472a74fe495b6ecd590a13582":{
      "scriptId":"u53"},
    "e8510bac8346479b9ea33a3032e76b5d":{
      "scriptId":"u54"},
    "876460e12f274062b04507f8bd11c748":{
      "scriptId":"u55"},
    "11cfcb10b7af41f88919f3c52bd09b1d":{
      "scriptId":"u56"},
    "e29c4f9b1bf34a5eb6129a61540717c0":{
      "scriptId":"u57"},
    "7f941e90cd40459b919044ee7baffa88":{
      "scriptId":"u58"},
    "454015f0ee3f4e8896116a058c17f353":{
      "scriptId":"u59"},
    "1e4ccc02360d4280a2c021e6e3488fe8":{
      "scriptId":"u60"},
    "015a8de6eec043beab07f8967a628034":{
      "scriptId":"u61"},
    "033bab825205441bb3df57cc050b6c3c":{
      "scriptId":"u62"},
    "d6d01e727bf144309f73d3628770cad9":{
      "scriptId":"u63"},
    "0bee2bc8230548f99a53f910e3bb7db6":{
      "scriptId":"u64"},
    "4ed291ee15e2466094186cf175779b8d":{
      "scriptId":"u65"},
    "d6fc7a2c2a2b4a938f6287f5820490aa":{
      "scriptId":"u66"},
    "e1bda09c596c4c90a6324b9e05d10ef6":{
      "scriptId":"u67"},
    "ded81012f7e048ba8bbcd5f358ea1898":{
      "scriptId":"u68"},
    "042f59d841f44ae7892647f125f8ab7b":{
      "scriptId":"u69"},
    "8577f75afc6746d19e06eacd38efaad0":{
      "scriptId":"u70"},
    "fcd10b7d561643ef978f2c15417ad68e":{
      "scriptId":"u71"},
    "edde79b9904044628971161ffb813530":{
      "scriptId":"u72"},
    "b63609f2f22c48c090015b9d01a2d653":{
      "scriptId":"u73"},
    "1795c77b6b8a461db44717ce3c05acfc":{
      "scriptId":"u74"},
    "e8ffe87da73b467f9308abdc34470668":{
      "scriptId":"u75"},
    "5e23422290164e64b96a433d0e43a7ea":{
      "scriptId":"u76"},
    "c13a83f6de64483eafdf0262edc6af57":{
      "scriptId":"u77"},
    "6d3c1bb0cbae44c3be5ecd450a8e0d48":{
      "scriptId":"u78"},
    "793b3121c4f94bb2b5cf0586a53f83ea":{
      "scriptId":"u79"},
    "15d635ef19014af8854306656bd94b18":{
      "scriptId":"u80"},
    "7c793123a3a5406a9d1a4d7dc9c277a7":{
      "scriptId":"u81"},
    "b77860d1bfa24665a40d77a3e8760361":{
      "scriptId":"u82"},
    "ebc98fb19c7541d09cb958d9ffe2ae2b":{
      "scriptId":"u83"},
    "369e7ea2f40f4cde94f273b2ac3b18b7":{
      "scriptId":"u84"},
    "e23902586343474bb15c95b577b26b40":{
      "scriptId":"u85"},
    "8fc2521e2a0542039e0d29d560fafe62":{
      "scriptId":"u86"},
    "574c456cca2a45cfa3c4ed3846ea5d86":{
      "scriptId":"u87"},
    "3c5b431a2fc74cba85bc380524789c5d":{
      "scriptId":"u88"},
    "18e93c5375e2437a8062ed92178f992c":{
      "scriptId":"u89"},
    "12eb6e46f04c4f3f8034a76c1637d47d":{
      "scriptId":"u90"},
    "f113087bc3c14c2ebc88b98b36771906":{
      "scriptId":"u91"},
    "d7457e76f80740e1a87f8fa96d2ea4b9":{
      "scriptId":"u92"},
    "5a701890e7924da3b30a099238f8021e":{
      "scriptId":"u93"},
    "ae69b32e3ec24917a2a8914d706242cd":{
      "scriptId":"u94"},
    "3ad30707ecdf4e15bd4c72ca9f808889":{
      "scriptId":"u95"},
    "b2a5aee6635e48d18e31ab5dbf797eb1":{
      "scriptId":"u96"},
    "154106a770cc4c6e8c17ff196f0c7b5c":{
      "scriptId":"u97"}}});